In [10]:
# this is 1D array
import numpy as np
array1d= np.array([11,21,32])
print("array1d =", array1d)

# this is 2d array
array2d = np.array([[41,62,13,94],
                    [15,6,70,88]])
print("array2d :")
for row in array2d:
    print(row)

# Space
print()

# Access and print elements from the NumPy array using their indices
print(array2d[0,-1])

# Space
print()

# change the value of the first element of array1d
array1d[0]=145
print(array1d)

# Space
print()

# change the of the third element of array2d of the second row
array2d[1,3] = 87
print("the third element of array2d of the second row :", array2d[1,3])

array1d = [11 21 32]
array2d :
[41 62 13 94]
[15  6 70 88]

94

[145  21  32]

the third element of array2d of the second row : 87


---

In [ ]:
import numpy as np

# create (edit) a numpy array
result1d = np.array([1, 3, 5, 7, 2, 4, 6, 8])

# reshape the array to 2D
result2d = result1d.reshape(2,4)
print("result1d :", result1d)
print("result2d :")
for row in result2d:
    print(row)

# Space
print()

# reshape the array to 3D
result3d = result2d.reshape(2, 2, 2)
print("result3d :")
for matrix in result3d:
    print(matrix)

# Space
print()

# flatten en array to 1D





result1d : [1 3 5 7 2 4 6 8]
result2d :
[1 3 5 7]
[2 4 6 8]

result3d :
[[1 3]
 [5 7]]
[[2 4]
 [6 8]]

